"""eden_control baseline: tenancy graph, principals, authz, audit, provisioning.

Baseline revision. It builds the control-plane tables from the ORM metadata
(single source of truth) and then adds two things the ORM cannot express:

* a WORM trigger making `audit_logs` append-only (tamper-evidence, spec #2);
* a partial unique index enforcing one current version per effective_key on
  the bi-temporal `tenant_configurations` (spec #1).

Subsequent schema changes MUST be explicit, autogenerated revisions.

Revision ID: 0001_eden_control
Revises:
Create Date: 2026-05-16
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

import eden.control.models  # noqa: F401  (registers tables on the metadata)
from eden.db.base import ControlBase

revision: str = "0001_eden_control"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CONTROL_SCHEMA = "eden_control"

_WORM_TRIGGER = f"""
CREATE OR REPLACE FUNCTION {CONTROL_SCHEMA}.audit_logs_block_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only (WORM); % rejected', TG_OP;
END;
$$;

CREATE TRIGGER trg_audit_logs_worm
BEFORE UPDATE OR DELETE OR TRUNCATE ON {CONTROL_SCHEMA}.audit_logs
FOR EACH STATEMENT EXECUTE FUNCTION {CONTROL_SCHEMA}.audit_logs_block_mutation();
"""

_BITEMPORAL_CURRENT_UNIQUE = f"""
CREATE UNIQUE INDEX uq_tenant_configurations_current
ON {CONTROL_SCHEMA}.tenant_configurations (effective_key)
WHERE is_current;
"""

# The pooled application role (locked decision #10) needs USAGE + DML on the
# control plane — it owns nothing and cannot CREATE, but the tenant router
# reads tenant_schemas and the audit logger appends to audit_logs on every
# request. Guarded so environments without the role (bare test DBs) still
# migrate; ALTER DEFAULT PRIVILEGES covers tables added by later revisions.
_APP_ROLE_GRANTS = f"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'eden_app') THEN
        GRANT USAGE ON SCHEMA {CONTROL_SCHEMA} TO eden_app;
        GRANT SELECT, INSERT, UPDATE, DELETE
            ON ALL TABLES IN SCHEMA {CONTROL_SCHEMA} TO eden_app;
        GRANT USAGE, SELECT
            ON ALL SEQUENCES IN SCHEMA {CONTROL_SCHEMA} TO eden_app;
        ALTER DEFAULT PRIVILEGES IN SCHEMA {CONTROL_SCHEMA}
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eden_app;
        ALTER DEFAULT PRIVILEGES IN SCHEMA {CONTROL_SCHEMA}
            GRANT USAGE, SELECT ON SEQUENCES TO eden_app;
    END IF;
END $$;
"""


def upgrade() -> None:
    bind = op.get_bind()
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{CONTROL_SCHEMA}"')
    ControlBase.metadata.create_all(bind=bind)
    op.execute(_WORM_TRIGGER)
    op.execute(_BITEMPORAL_CURRENT_UNIQUE)
    op.execute(_APP_ROLE_GRANTS)


def downgrade() -> None:
    bind = op.get_bind()
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_audit_logs_worm ON {CONTROL_SCHEMA}.audit_logs"
    )
    op.execute(
        f"DROP FUNCTION IF EXISTS {CONTROL_SCHEMA}.audit_logs_block_mutation()"
    )
    ControlBase.metadata.drop_all(bind=bind)
